name = "lingoloop-api"
main = "src/index.ts"
compatibility_date = "2024-07-01"
compatibility_flags = ["nodejs_compat"]

[vars]
CORS_ORIGIN = "*"

[env.dev]
vars = { CORS_ORIGIN = "http://localhost:3000" }
